version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Docker/server.Dockerfile

  client:
    build:
      context: .
      dockerfile: Docker/client.Dockerfile
    depends_on:
      - server